spring:
  datasource:
    url: jdbc:sqlserver://javatechie-prac.database.windows.net:1433;database=javatechiedb;user=javatechie@javatechie-prac;password=password@123;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: javatechie
    password: password@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


